feat: [CSRS-227] refactoring questionnaire
bcgov/jag-csrs-portal-public pull request #16
Opened 2021-11-22 19:18 UTC by kkadaru

# Description

This PR includes the following proposed change(s):

- CSRS-227 refactoring questionnaire

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [X] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2021-11-22 22:25 UTC, skiselev1 reviewed
Thank you for cleaning some issues with scss! Very clean source code. I did not find questionnaire.html. Did you refactor it as well?

2021-11-22 23:21 UTC, skiselev1 approved these changes
Good job! I don't have any comments.

2021-11-23 00:46 UTC, NovaVic requested changes
One minor modification request on dynamic/env specific BCeID link please. Thanks!

2021-11-23 00:46 UTC, NovaVic commented on src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
> +    this.bceIdLink = 'https://www.bceid.ca/';
FYI:
We may have to pass/load environment specific values here.
The link is not same for dev, test and prod.

2021-11-23 18:03 UTC, kkadaru commented
>

2021-11-23 22:13 UTC, merged