Initial Upload
bcgov/jag-csrs-portal-public pull request #6
Opened 2021-11-05 19:27 UTC by skiselev1

Initial upload is done. Could you please review it?

Thanks,
Sergey

2021-11-06 05:58 UTC, NovaVic requested changes
Lots of cleanup to do.
Also source and destination of merge are not the right ones.

2021-11-09 15:56 UTC, skiselev1 commented on src/frontend/csrs-portal/package.json
> +    "@azure/ai-form-recognizer": "^3.1.0",
Thank you! it was cleaned.

2021-11-09 15:56 UTC, skiselev1 commented on src/frontend/csrs-portal/package.json
> +    "faker": "^5.5.3",
Fake reference was removed

2021-11-09 15:56 UTC, skiselev1 commented on src/frontend/csrs-portal/src/assets/i18n/en.json
> +    "description1": "The online tool for submitting and resolving your BC Violation Ticket disputes.",
it was cleaned

2021-11-09 18:33 UTC, KyleKayfish commented on src/frontend/csrs-portal/README.md
> +Clone the CSRS repository into a project directory GitKraken or the terminal by typing:
Readme does not need to be so granular to specify a Git browser or how to clone.  Can simply state clone repo. 
However as this is a public repo it should be forked

2021-11-22 19:16 UTC, skiselev1 commented
We don't need to merge from main to repo-mountie/add-compliance. This PR was created in error.

2021-11-22 19:16 UTC, closed without merging